version: "3.9"

services:
  wall:
    build: ./
    restart: always
    command: "npm run dev"
    ports:
      - 3001:3001
      - 9229:9229
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www/the-wall